server:
  servlet:
    context-path: /healthcare/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        xml: application/xml
  jackson:
    serialization:
      indent-output: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
  show-actuator: true